version: '3.8'

services:

  django:
    container_name: django
    build: 
      context: ./backend
    command: python manage.py runserver
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=jankni34tnio4nt
      - ALLOWED_HOSTS=localhost,127.0.0.1