services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
    healthCheckPath: /admin/

# storage:
#   - name: django-sqlite
#     mountPath: /app/db.sqlite3